### ISSUE TITLE
[BUG] vyos-rolling/vyos_protocols_bgp_neighbor  Incorrect validation on the 'identifier.neighbor' option

### ISSUE THREAD

**Issue by houndsolo** [thomasfinstad/terraform-provider-vyos-rolling#222]
# Description

Incorrect validation on the 'identifier.neighbor' variable

# Versions

- OpenTofu: 1.8.2
- Provider: 2.11.202409250
- VyOS: 1.5-rolling-202402060022

## Minimal terraform code
```hcl
terraform {
  required_providers {
    vyos = {
      source = "registry.terraform.io/thomasfinstad/vyos-rolling"
      version = "2.11.202409250"
    }
  }
}
provider "vyos" {
  endpoint ="https://10.20.1.11"
  api_key  = "test_api_key"
  certificate = {
    disable_verify = true
  }
  default_timeouts = 2
}

resource "vyos_protocols_bgp" "enable_bgp" {
  system_as = 1
}

resource "vyos_protocols_bgp_neighbor" "bgp_neighbor" {
  depends_on = [vyos_protocols_bgp.enable_bgp]
  identifier = {
    neighbor = "10.1.1.1"
  }
  remote_as = 2
}


```
```
│ Error: Invalid Attribute Value Match
│
│   with vyos_protocols_bgp_neighbor.bgp_neighbor,
│   on bug.tf line 22, in resource "vyos_protocols_bgp_neighbor" "bgp_neighbor":
│   22: resource "vyos_protocols_bgp_neighbor" "bgp_neighbor" {
│
│ Attribute identifier.neighbor illegal character in  neighbor, value must match: ^[a-zA-Z0-9-_]*$, got: 10.1.1.1

╵
```

If i change the regex inner brackets to [0-9.] then it works as expected. :) at least for ipv4

https://github.com/thomasfinstad/terraform-provider-vyos-rolling/blob/bd6ba402c9da014e804f77238b138bcb3d2d06dd/internal/terraform/resource/autogen/named/protocols/bgp-neighbor/resourcemodel/protocols-bgp-neighbor.go#L157

I have also noticed this happening with vyos_protocols_bgp_address_family_ipv4_unicast_network.

**Comment by thomasfinstad** [comment]
Sorry about the delay, should now be fixed in v5.0.202410150
