### ISSUE TITLE
[BUG] vyos_service_dhcp_server_shared_network_name_subnet doesn't allow CIDR subnets

### ISSUE THREAD

**Issue by Spanfile** [thomasfinstad/terraform-provider-vyos-rolling#224]
***Voting for Prioritization***

- *Please vote on this issue by adding a 👍 reaction to the original post to help the community and maintainers prioritize this request.*
- *Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.*

***Volunteering to Work on This Issue***

- *If you are interested in working on this issue, please leave a comment.*
- *If this would be your first contribution, please review the contribution guide.*

# Description

VyOS ipv4net/ipv6net CIDR subnets (i.e. `192.168.128.0/24`) aren't validated correctly because the regex doesn't allow forward slashes in the value.

# Versions

- Terraform: v1.9.8
- Provider: v5.2.202410181
- VyOS: 1.5-rolling-202410180006

# Reproduction

## Minimal terraform code
```hcl
resource "vyos_service_dhcp_server_shared_network_name_subnet" "dhcp_lan_subnet" {
  identifier = {
    shared_network_name = "LAN"
    subnet              = "192.168.128.0/24"
  }
}
```
```
│ Error: Invalid Attribute Value Match
│
│   with vyos_service_dhcp_server_shared_network_name_subnet.dhcp_lan_subnet,
│   on 10-dhcp.tf line 11, in resource "vyos_service_dhcp_server_shared_network_name_subnet" "dhcp_lan_subnet":
│   11: resource "vyos_service_dhcp_server_shared_network_name_subnet" "dhcp_lan_subnet" {
│
│ Attribute identifier.subnet illegal character in  subnet, value must match: ^[.:a-zA-Z0-9-_]+$, got: 192.168.128.0/24
```

**Comment by thomasfinstad** [comment]
I have a working fix for this issue ready, however the need for support in merging resources together needs to be in place before this issue can really be fixed, as the dhcp server config is dependant on configs across several resources being set during the same commit. Once that is in place this should also work.
